/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_example_com_jni_jnidemo */

#ifndef _Included_c_example_com_jni_jnidemo
#define _Included_c_example_com_jni_jnidemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_example_com_jni_jnidemo
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_c_example_com_jni_jnidemo_SayHello
  (JNIEnv *, jclass);

/*
 * Class:     c_example_com_jni_jnidemo
 * Method:    getStudentInfo
 * Signature: ()Lc/example/com/jni/Student;
 */
JNIEXPORT jobject JNICALL Java_c_example_com_jni_jnidemo_getStudentInfo
  (JNIEnv *, jclass);

/*
 * Class:     c_example_com_jni_jnidemo
 * Method:    updateStudentInfo
 * Signature: (Lc/example/com/jni/Student;)Lc/example/com/jni/Student;
 */
JNIEXPORT jobject JNICALL Java_c_example_com_jni_jnidemo_updateStudentInfo
  (JNIEnv *, jclass, jobject);

//JNIEXPORT jobject JNICALL
//Java_c_example_com_jni_jnidemo_getPeopleInfo
//        (JNIEnv *, jclass , jobject ) ;

/*
 * Class:     c_example_com_jni_jnidemo
 * Method:    getStudentInfo
 * Signature: ()Lc/example/com/jni/Student;
 */
JNIEXPORT jobject JNICALL Java_c_example_com_jni_jnidemo_getPeopleInfo
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
